name:                insert-molecule
version:             0.1.0.0
github:              "wurthel/insert-molecule"
license:             BSD3
author:              "Vusal Salmanov"
maintainer:          "salmanov.vh@gmail.com"
copyright:           "2019 Vusal Salmanov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wurthel/insert-molecule#readme>

dependencies:
- base >= 4.7 && < 5
- random
- directory
- containers
- deepseq
- strict
- fclabels
- process

library:
  source-dirs: src

executables:
  insert-molecule-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - insert-molecule